<a href="https://colab.research.google.com/github/WaHMugdha/MoodBites/blob/main/moodbites_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: load dataset from drive

import pandas as pd
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Load the dataset from a CSV file on Google Drive
data_path = '/content/drive/My Drive/Kaggle/moodbites_data_final.csv'
data = pd.read_csv(data_path)
data.describe()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Unnamed: 0  online_order    book_table          rate         votes  \
count  1.320051e+06  1.320051e+06  1.320051e+06  1.320051e+06  1.320051e+06   
mean   2.742973e+04  6.296355e-01  3.013368e-01  5.531482e-01  1.026741e+00   
std    1.449174e+04  4.829025e-01  4.588389e-01  4.281624e-01  2.447005e+00   
min    0.000000e+00  0.000000e+00  0.000000e+00 -2.444461e+00 -3.529318e-01   
25%    1.541000e+04  0.000000e+00  0.000000e+00  3.484885e-01 -2.347477e-01   
50%    2.885000e+04  1.000000e+00  0.000000e+00  5.967508e-01 -2.699264e-02   
75%    4.014800e+04  1.000000e+00  1.000000e+00  8.450130e-01  1.274276e+00   
max    5.171600e+04  1.000000e+00  1.000000e+00  1.217406e+00  2.058679e+01   

               cost          type          city  Sentiment_Score  
count  1.313567e+06  1.320051e+06  1.320051e+06     1.320051e+06  
mean   5.352970e-01  2.920444e+00  1.500306e+01     5.393571e-01  
std    1.155419e+00  1.325064e+00  8.038767e+00     5.338563e-01  
min   -1.174515e+00  0.000000e+00  0.000000e+00    -9.933000e-01  
25%   -3.541821e-01  2.000000e+00  9.000000e+00     1.779000e-01  
50%    1.015581e-01  2.000000e+00  1.600000e+01     8.153000e-01  
75%    1.240909e+00  4.000000e+00  2.100000e+01     9.382000e-01  
max    1.240655e+01  6.000000e+00  2.900000e+01     9.988000e-01

In [ ]:
data['Sentiment_Score'].unique()

array([ 0.743 ,  0.9486,  0.7964, ..., -0.4222, -0.3079, -0.1774])

In [ ]:
# prompt: add new column
# sentiment_class = {0 : 'very bad', 1 : 'bad', 2 : 'neutral', 3 : 'good', 4: 'very good'}
def sentiment(sentiment_score):
  if sentiment_score >= -1 and sentiment_score <= -0.8:
    return 0
  elif sentiment_score > -0.8 and sentiment_score <= -0.2:
    return 1
  elif sentiment_score > -0.2 and sentiment_score <= 0.2:
    return 2
  elif sentiment_score > 0.2 and sentiment_score <= 0.8:
    return 3
  elif sentiment_score > 0.8 and sentiment_score <= 1:
    return 4



data['Sentiment_Class'] = data['Sentiment_Score'].apply(sentiment)
data.head(5)

Unnamed: 0                                                url  \
0           0  https://www.zomato.com/bangalore/jalsa-banasha...   
1           0  https://www.zomato.com/bangalore/jalsa-banasha...   
2           0  https://www.zomato.com/bangalore/jalsa-banasha...   
3           0  https://www.zomato.com/bangalore/jalsa-banasha...   
4           0  https://www.zomato.com/bangalore/jalsa-banasha...   

                                             address   name  online_order  \
0  942, 21st Main Road, 2nd Stage, Banashankari, ...  Jalsa             1   
1  942, 21st Main Road, 2nd Stage, Banashankari, ...  Jalsa             1   
2  942, 21st Main Road, 2nd Stage, Banashankari, ...  Jalsa             1   
3  942, 21st Main Road, 2nd Stage, Banashankari, ...  Jalsa             1   
4  942, 21st Main Road, 2nd Stage, Banashankari, ...  Jalsa             1   

   book_table      rate     votes                           phone  \
0           1  0.720882  0.611201  080 42297555\r\n+91 9743772233   
1           1  0.720882  0.611201  080 42297555\r\n+91 9743772233   
2           1  0.720882  0.611201  080 42297555\r\n+91 9743772233   
3           1  0.720882  0.611201  080 42297555\r\n+91 9743772233   
4           1  0.720882  0.611201  080 42297555\r\n+91 9743772233   

       location      rest_type  \
0  Banashankari  Casual Dining   
1  Banashankari  Casual Dining   
2  Banashankari  Casual Dining   
3  Banashankari  Casual Dining   
4  Banashankari  Casual Dining   

                                          dish_liked  \
0  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
1  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
2  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
3  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   
4  Pasta, Lunch Buffet, Masala Papad, Paneer Laja...   

                         cuisines      cost  \
0  North Indian, Mughlai, Chinese  0.557298   
1  North Indian, Mughlai, Chinese  0.557298   
2  North Indian, Mughlai, Chinese  0.557298   
3  North Indian, Mughlai, Chinese  0.557298   
4  North Indian, Mughlai, Chinese  0.557298   

                                        reviews_list menu_item  type  city  \
0  ('Rated 4.0', 'RATED\n  A beautiful place to d...        []     0     1   
1  ('Rated 4.0', 'RATED\n  I was here for dinner ...        []     0     1   
2  ('Rated 2.0', 'RATED\n  Its a restaurant near ...        []     0     1   
3  ('Rated 4.0', 'RATED\n  We went here on a week...        []     0     1   
4  ('Rated 5.0', 'RATED\n  The best thing about t...        []     0     1   

   Sentiment_Score  Sentiment_Class  
0           0.7430                3  
1           0.9486                4  
2           0.7964                3  
3           0.9622                4  
4           0.9461                4

In [ ]:
data['Sentiment_Class'].unique()

array([3, 4, 2, 0, 1])

In [ ]:
data.columns

Index(['Unnamed: 0', 'url', 'address', 'name', 'online_order', 'book_table',
       'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked',
       'cuisines', 'cost', 'reviews_list', 'menu_item', 'type', 'city',
       'Sentiment_Score', 'Sentiment_Class'],
      dtype='object')

In [ ]:
data.isnull().sum()

Unnamed: 0              0
url                     0
address                 0
name                    0
online_order            0
book_table              0
rate                    0
votes                   0
phone               22192
location                0
rest_type            7178
dish_liked         227876
cuisines               87
cost                 6484
reviews_list            0
menu_item               0
type                    0
city                    0
Sentiment_Score         0
Sentiment_Class         0
dtype: int64

In [ ]:
data.drop(columns=['Unnamed: 0', 'address', 'phone', 'dish_liked', 'menu_item'], axis=1, inplace=True)
data.isnull().sum()

url                   0
name                  0
online_order          0
book_table            0
rate                  0
votes                 0
location              0
rest_type          7178
cuisines             87
cost               6484
reviews_list          0
type                  0
city                  0
Sentiment_Score       0
Sentiment_Class       0
dtype: int64

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
data['rest_type'] = imputer.fit_transform(data['rest_type'].values.reshape(-1, 1))
data['cuisines'] = imputer.fit_transform(data['cuisines'].values.reshape(-1, 1))
impute = SimpleImputer(strategy='median')
data['cost'] = imputer.fit_transform(data[['cost']])
data.isnull().sum()

url                0
name               0
online_order       0
book_table         0
rate               0
votes              0
location           0
rest_type          0
cuisines           0
cost               0
reviews_list       0
type               0
city               0
Sentiment_Score    0
Sentiment_Class    0
dtype: int64

In [ ]:
#label encoding 'location', 'rest_type', 'cuisines'
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['name'] = label_encoder.fit_transform(data['name'])
data['location'] = label_encoder.fit_transform(data['location'])
data['rest_type'] = label_encoder.fit_transform(data['rest_type'])
data['cuisines'] = label_encoder.fit_transform(data['cuisines'])
data.head(5)

url  name  online_order  \
0  https://www.zomato.com/bangalore/jalsa-banasha...  2933             1   
1  https://www.zomato.com/bangalore/jalsa-banasha...  2933             1   
2  https://www.zomato.com/bangalore/jalsa-banasha...  2933             1   
3  https://www.zomato.com/bangalore/jalsa-banasha...  2933             1   
4  https://www.zomato.com/bangalore/jalsa-banasha...  2933             1   

   book_table      rate     votes  location  rest_type  cuisines      cost  \
0           1  0.720882  0.611201         1         24      1972  0.557298   
1           1  0.720882  0.611201         1         24      1972  0.557298   
2           1  0.720882  0.611201         1         24      1972  0.557298   
3           1  0.720882  0.611201         1         24      1972  0.557298   
4           1  0.720882  0.611201         1         24      1972  0.557298   

                                        reviews_list  type  city  \
0  ('Rated 4.0', 'RATED\n  A beautiful place to d...     0     1   
1  ('Rated 4.0', 'RATED\n  I was here for dinner ...     0     1   
2  ('Rated 2.0', 'RATED\n  Its a restaurant near ...     0     1   
3  ('Rated 4.0', 'RATED\n  We went here on a week...     0     1   
4  ('Rated 5.0', 'RATED\n  The best thing about t...     0     1   

   Sentiment_Score  Sentiment_Class  
0           0.7430                3  
1           0.9486                4  
2           0.7964                3  
3           0.9622                4  
4           0.9461                4

# Support Vector Machine Model(SVM)
Support Vector Machines (SVM) can be used for multiclass classification tasks using various strategies such as One-vs-One (OvO) or One-vs-All (OvA)

In [ ]:
data.columns

Index(['url', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'location', 'rest_type', 'cuisines', 'cost', 'reviews_list', 'type',
       'city', 'Sentiment_Score', 'Sentiment_Class'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

X = data[['online_order', 'book_table', 'rate', 'votes', 'rest_type', 'cuisines', 'cost']]
y = data['Sentiment_Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# svm_model = SVC(kernel='linear', C=1.0, decision_function_shape='ovr')

# svm_model.fit(X_train, y_train)

In [ ]:
import tensorflow as tf

# Assuming X_train and y_train are your training features and labels
# Create a Sequential model
model = tf.keras.Sequential()

# Add a Dense layer with one unit (for binary classification) and a linear activation function
model.add(tf.keras.layers.Dense(units=1, activation='linear'))

# Compile the model with a hinge loss function and Adam optimizer
model.compile(loss='hinge', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)


Epoch 1/10
26401/26401 [==============================] - 68s 3ms/step - loss: 0.0338 - accuracy: 0.0896 - val_loss: 0.0295 - val_accuracy: 0.0896
Epoch 2/10
26401/26401 [==============================] - 60s 2ms/step - loss: 0.0295 - accuracy: 0.0896 - val_loss: 0.0295 - val_accuracy: 0.0896
Epoch 3/10
26401/26401 [==============================] - 58s 2ms/step - loss: 0.0295 - accuracy: 0.0896 - val_loss: 0.0295 - val_accuracy: 0.0896
Epoch 4/10
26401/26401 [==============================] - 76s 3ms/step - loss: 0.0295 - accuracy: 0.0896 - val_loss: 0.0295 - val_accuracy: 0.0896
Epoch 5/10
26401/26401 [==============================] - 60s 2ms/step - loss: 0.0295 - accuracy: 0.0896 - val_loss: 0.0295 - val_accuracy: 0.0896
Epoch 6/10
26401/26401 [==============================] - 62s 2ms/step - loss: 0.0295 - accuracy: 0.0896 - val_loss: 0.0295 - val_accuracy: 0.0896
Epoch 7/10
26401/26401 [==============================] - 59s 2ms/step - loss: 0.0295 - accuracy: 0.0896 - val_loss: 0

In [ ]:
y_pred = model.predict(X_test)

# import numpy as np
# y_pred = model.predict(X_test)
# y_pred_labels = np.round(y_pred).flatten()
# accuracy_score(y_test, y_pred)

8251/8251 [==============================] - 25s 3ms/step


147459     4
684963     2
979714     4
44241      2
1007730    4
          ..
610463     1
165843     4
208778     4
941077     0
1273647    4
Name: Sentiment_Class, Length: 264011, dtype: int64

In [ ]:
data.shape

In [ ]:
y_test

147459     4
684963     2
979714     4
44241      2
1007730    4
          ..
610463     1
165843     4
208778     4
941077     0
1273647    4
Name: Sentiment_Class, Length: 264011, dtype: int64

In [ ]:
y_pred

array([[2904.4575],
       [ 356.2622],
       [3781.5667],
       ...,
       [2643.465 ],
       [1057.5646],
       [1360.473 ]], dtype=float32)